// @plugin mentions: find them, apply them safely, and ignore text that only looks like one.
const m = require('../server/mentions.js');
let bad = 0; const ok = (n, c, x) => { console.log((c ? 'PASS ' : 'FAIL ') + n + (c ? '' : '  -> ' + String(x).slice(0, 200))); if (!c) bad++; };
const f = (t, c) => m.find(t, c);
ok('@github is found', f('@github look at my repo').groups.join() === 'github');
ok('a mention in the middle is found', f('please use @github to read it').groups.join() === 'github');
ok('case does not matter', f('@GitHub read it').groups.join() === 'github');
ok('an alias works (@repo -> github)', f('@repo list my files').groups.join() === 'github');
ok('two plugins at once', f('@github and @search please').groups.join() === 'github,search');
ok('the same plugin twice counts once', f('@github @github @git').groups.join() === 'github');
ok('after punctuation', f('ok, (@github) now').groups.join() === 'github' && f('hi:@search').groups.join() === 'search');
ok('a custom tool is found', f('@notion_page read 12', ['notion_page']).tools.join() === 'notion_page');
ok('the model-facing @x_name spelling resolves to the saved plugin', f('@x_notion_page run this', ['notion_page']).tools.join() === 'notion_page');
ok('custom x_ mention works after text and punctuation', f('please run @x_notion_page, now', ['notion_page']).tools.join() === 'notion_page');
ok('a custom tool is found in any case', f('@Notion_Page read', ['notion_page']).tools.join() === 'notion_page');
ok('an unknown custom tool is ignored', f('@notion_page read', []).tools.length === 0);
ok('an email address is NOT a mention', f('mail me at bob@github.com').groups.length === 0 && f('a.b@search.io').groups.length === 0);
ok('an email-like word with a dot is NOT a mention', f('x@github.com and @github').groups.join() === 'github');
ok('@everyone is ignored', f('@everyone hi').names.length === 0);
ok('@terminal can never be called by a mention', f('@terminal rm -rf').groups.length === 0 && f('@terminal rm -rf').names.length === 0);
ok('a mention inside a word is ignored', f('user@github').groups.length === 0);
ok('empty and odd input is safe', f('').names.length === 0 && f(null).names.length === 0 && f(undefined).names.length === 0 && f(12345).names.length === 0);
ok('a very long message is safe and fast', (() => { const t = Date.now(); f('@github '.repeat(5000)); return Date.now() - t < 200; })());
ok('at most 6 mentions', f('@github @search @tools @skills @mcp @platform @git').names.length <= 6);
ok('a trailing dot or question mark still works', f('what is in @github?').groups.join() === 'github' && f('use @github.').groups.join() === 'github');

const A = () => ({ github: false, search: false, tools: true, skills: false, mcp: false, platform: false, terminal: false });
let a = A(), fnd = f('@github read my repo'), d = m.apply(a, fnd, { canTools: true, creditsOk: true });
ok('a mention turns the plugin on when its switch was off', a.github === true && d.forced.join() === 'github');
ok('terminal stays off', a.terminal === false);
a = A(); d = m.apply(a, f('@github read'), { canTools: false, creditsOk: true });
ok('a model that cannot run tools is NOT forced', a.github === false && d.blocked.length === 1 && /cannot run tools/.test(d.blocked[0].why));
a = A(); d = m.apply(a, f('@github read'), { canTools: true, creditsOk: false });
ok('no credits: a paid plugin is NOT forced', a.github === false && /credits/.test(d.blocked[0].why));
a = A(); d = m.apply(a, f('@skills use it'), { canTools: true, creditsOk: false });
ok('no credits: a free plugin still works', a.skills === true && d.forced.join() === 'skills');
a = A(); d = m.apply(a, f('@notion_page read', ['notion_page']), { canTools: true, creditsOk: false });
ok('a custom tool is offered even with no credits', a.skills === true && a.mentionTools.join() === 'notion_page' && d.forced.join() === 'notion_page');
a = A(); a.github = true; d = m.apply(a, f('@github read'), { canTools: true, creditsOk: true });
ok('already on: nothing is changed and nothing is reported as forced', a.github === true && d.forced.length === 0);
a = A(); d = m.apply(a, f('hello there'), { canTools: true, creditsOk: true });
ok('no mention: nothing changes', JSON.stringify(a) === JSON.stringify(A()) && d.forced.length === 0 && d.blocked.length === 0);

fnd = f('@github look at it'); d = m.apply(A(), fnd, { canTools: true, creditsOk: true });
ok('the hint tells the AI not to say it cannot access the plugin', /USE their tools/.test(m.hint(fnd, d)) && /@github/.test(m.hint(fnd, d)) && /do not say you cannot access/.test(m.hint(fnd, d)));
fnd = f('@github look'); d = m.apply(A(), fnd, { canTools: false, creditsOk: true });
ok('no hint when the plugin could not be turned on', m.hint(fnd, d) === '');
fnd = f('@notion_page x', ['notion_page']); d = m.apply(A(), fnd, { canTools: true, creditsOk: true });
ok('the hint names a custom tool as x_name', /x_notion_page/.test(m.hint(fnd, d)));
ok('custom mention instructions tell the model to ask rather than invent missing arguments', /required argument is missing, ask the user/.test(m.hint(fnd, d)));
ok('no hint when nothing was mentioned', m.hint(f('hello'), { forced: [], blocked: [] }) === '');
console.log(bad ? bad + ' FAILED' : 'ALL PASSED'); process.exit(bad ? 1 : 0);
