// The dependency check must run on every start/update, install only what is missing, and never loop forever.
const path = require('path'), setup = require('../server/setup.js');
let bad = 0, n = 0; const ok = (name, c, x) => { n++; console.log((c ? 'PASS ' : 'FAIL ') + name + (c ? '' : '  -> ' + String(x).slice(0, 200))); if (!c) bad++; };
const W = 'win32', env = {};
ok('first run checks', setup.shouldAutoSetup(W, env, null, '1.0'));
ok('it CHECKS AGAIN after a successful setup (a file may have been deleted)', setup.shouldAutoSetup(W, env, { ok: true, tries: 0, version: '1.0' }, '1.0'));
ok('it checks again after an update', setup.shouldAutoSetup(W, env, { ok: true }, '1.1'));
ok('after 3 failed tries on the SAME version it stops (no endless loop)', !setup.shouldAutoSetup(W, env, { ok: false, tries: 3, version: '1.0' }, '1.0'));
ok('a NEW version gets a fresh set of tries after failures', setup.shouldAutoSetup(W, env, { ok: false, tries: 3, version: '1.0' }, '1.1'));
ok('2 failed tries still retry', setup.shouldAutoSetup(W, env, { ok: false, tries: 2, version: '1.0' }, '1.0'));
ok('never on Linux or Mac', !setup.shouldAutoSetup('linux', env, null, '1') && !setup.shouldAutoSetup('darwin', env, null, '1'));
ok('can be switched off', !setup.shouldAutoSetup(W, { PHOLAMA_NO_AUTOSETUP: '1' }, null, '1'));
ok('nothing missing = nothing installed', setup.missingNow({ llamaServer: true, python: { installed: true } }).length === 0);
ok('missing python is found', setup.missingNow({ llamaServer: true, python: { installed: false } }).join() === 'python');
ok('missing engine is found', setup.missingNow({ python: { installed: true } }).join() === 'engine');
ok('ollama counts as an engine', setup.missingNow({ ollama: true, python: { installed: true } }).length === 0);
ok('both missing', setup.missingNow({}).join() === 'engine,python');
const script = path.join(__dirname, '..', 'tools', 'mcp', 'pholama_files.py');
ok('the bundled tool server really starts with a working python', setup.toolServerCheck('python3', script).ok);
const bad2 = setup.toolServerCheck('definitely-not-python-xyz', script);
ok('a missing python is reported, not hidden', !bad2.ok && !!bad2.error, JSON.stringify(bad2));
ok('a script that is not a tool server is reported', !setup.toolServerCheck('python3', path.join(__dirname, 'setup-recheck.test.js')).ok);
console.log(bad ? bad + ' FAILED' : 'ALL PASSED (' + n + ')'); process.exit(bad ? 1 : 0);
